<?php
session_start();

// Check if the user is an administrator
if (!isset($_SESSION['role_id']) || $_SESSION['role_id'] != '1') {
    header("Location: login.php");
    exit();
}

require 'admin_conn.php'; 

$errors = [];  
$success = ""; 

// Fetch all audit reports to display
$reports = $conn->query("SELECT * FROM audit_reports ORDER BY created_at DESC");

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Audit Reports</title>
    <link rel="stylesheet" href="admin.css">
</head>
<body>
    <header>
        <div class="navbar">
            <div class="logo">ABC Company</div>
            <div class="nav-links">
                <b><?php echo htmlspecialchars($_SESSION['username']); ?></b>
                <a href="/login/logout.php">Logout</a>
                <a href="/login/dashboard.php">Return</a>
            </div>
        </div>
    </header>

    <?php if ($errors): ?>
        <div class="error">
            <?php foreach ($errors as $error): ?>
                <p><?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if ($success): ?>
        <div class="success">
            <p><?php echo $success; ?></p>
        </div>
    <?php endif; ?>

    <h2>Audit Reports</h2>
    <table class="form-table">
        <tr>
            <th>Report ID</th>
            <th>Report Name</th>
            <th>Generated By</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Actions</th>
        </tr>
        <?php while ($report = $reports->fetch_assoc()): ?>
            <tr>
                <td><?php echo $report['report_id']; ?></td>
                <td><?php echo htmlspecialchars($report['report_name']); ?></td>
                <td><?php echo htmlspecialchars($report['generated_by']); ?></td>
                <td><?php echo htmlspecialchars($report['status']); ?></td>
                <td><?php echo htmlspecialchars($report['created_at']); ?></td>
                <td>
                    <!-- View Report Button -->
                    <form method="GET" action="view_report.php" style="display:inline;">
                        <input type="hidden" name="report_id" value="<?php echo $report['report_id']; ?>">
                        <button type="submit">View</button>
                    </form>
                    <!-- Download Report Button -->
                    <form method="POST" action="download_report.php" style="display:inline;">
                        <input type="hidden" name="report_id" value="<?php echo $report['report_id']; ?>">
                        <button type="submit">Download</button>
                    </form>
                </td>
            </tr>
        <?php endwhile; ?>
    </table>

</body>
</html>
